# Generated by Django 5.1.6 on 2025-02-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_rename_organization_agent_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_oragnisor',
            field=models.BooleanField(default=True),
        ),
    ]
